import { InterviewState } from "../consts.js";
import type { Device, DeviceState } from "../types.js";

export const COORDINATOR: Device = {
    disabled: false,
    endpoints: {
        "1": {
            bindings: [],
            clusters: {
                input: ["genBasic", "genIdentify", "genOnOff", "genTime", "genOta", "26", "lightingColorCtrl"],
                output: [
                    "genBasic",
                    "genIdentify",
                    "genGroups",
                    "genScenes",
                    "genOnOff",
                    "genLevelCtrl",
                    "genPollCtrl",
                    "lightingColorCtrl",
                    "msIlluminanceMeasurement",
                    "msTemperatureMeasurement",
                    "msRelativeHumidity",
                    "msOccupancySensing",
                    "ssIasZone",
                    "haMeterIdentification",
                    "haApplianceStatistics",
                    "haElectricalMeasurement",
                    "seMetering",
                    "touchlink",
                    "manuSpecificLegrandDevices",
                    "manuSpecificSamsungAccelerometer",
                ],
            },
            configured_reportings: [],
            scenes: [],
        },
        "242": {
            bindings: [],
            clusters: {
                input: [],
                output: ["greenPower"],
            },
            configured_reportings: [],
            scenes: [],
        },
    },
    friendly_name: "Coordinator",
    ieee_address: "0xe0798dfffe232421",
    interview_completed: true,
    interview_state: InterviewState.Successful,
    interviewing: false,
    network_address: 0,
    supported: true,
    type: "Coordinator",
    power_source: undefined,
    software_build_id: undefined,
    date_code: undefined,
    model_id: undefined,
    manufacturer: undefined,
};

export const BASIC_ROUTER: Device = {
    date_code: "20210320",
    definition: {
        description: "Zigbee two way smart switch",
        exposes: [
            // @ts-expect-error bad ZHC typing
            {
                features: [
                    {
                        access: 7,
                        description: "On/off state of the switch",
                        label: "State",
                        name: "state",
                        property: "state",
                        type: "binary",
                        value_off: "OFF",
                        value_on: "ON",
                        value_toggle: "TOGGLE",
                    },
                ],
                type: "switch",
            },
            {
                access: 1,
                category: "diagnostic",
                description: "Link quality (signal strength)",
                label: "Linkquality",
                name: "linkquality",
                property: "linkquality",
                type: "numeric",
                unit: "lqi",
                value_max: 255,
                value_min: 0,
            },
        ],
        model: "ZBMINI",
        options: [
            {
                access: 2,
                description: "State actions will also be published as 'action' when true (default false).",
                label: "State action",
                name: "state_action",
                property: "state_action",
                type: "binary",
                value_off: false,
                value_on: true,
            },
        ],
        source: "native",
        supports_ota: false,
        vendor: "SONOFF",
    },
    disabled: false,
    endpoints: {
        "1": {
            bindings: [
                {
                    cluster: "genOnOff",
                    target: {
                        endpoint: 1,
                        ieee_address: "0xe0798dfffe232421",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: ["genBasic", "genIdentify", "genGroups", "genScenes", "genOnOff", "manuSpecificAmazonWWAH"],
                output: ["genOta"],
            },
            configured_reportings: [
                {
                    attribute: "onOff",
                    cluster: "genOnOff",
                    maximum_report_interval: 65000,
                    minimum_report_interval: 0,
                    reportable_change: 1,
                },
            ],
            scenes: [],
        },
        "242": {
            bindings: [],
            clusters: {
                input: [],
                output: ["greenPower"],
            },
            configured_reportings: [],
            scenes: [],
        },
    },
    friendly_name: "Kitchen Light Switch",
    ieee_address: "0x00124b0024c21111",
    interview_completed: true,
    interview_state: InterviewState.Successful,
    interviewing: false,
    manufacturer: "SONOFF",
    model_id: "01MINIZB",
    network_address: 60284,
    power_source: "Mains (single phase)",
    software_build_id: "2.0.0",
    supported: true,
    type: "Router",
};

export const BASIC_ENDDEVICE: Device = {
    date_code: "20240123",
    definition: {
        description: "VALLHORN wireless motion sensor",
        exposes: [
            {
                access: 5,
                description: "Indicates whether the device detected occupancy",
                label: "Occupancy",
                name: "occupancy",
                property: "occupancy",
                type: "binary",
                value_off: false,
                value_on: true,
            },
            {
                access: 5,
                description: "Measured illuminance",
                label: "Illuminance",
                name: "illuminance",
                property: "illuminance",
                type: "numeric",
                unit: "lx",
            },
            {
                access: 1,
                description: "Raw measured illuminance",
                label: "Illuminance raw",
                name: "illuminance_raw",
                property: "illuminance_raw",
                type: "numeric",
            },
            {
                access: 2,
                category: "config",
                description:
                    "Initiate device identification. This device is asleep by default.You may need to wake it up first before sending the identify command.",
                label: "Identify",
                name: "identify",
                property: "identify",
                type: "enum",
                values: ["identify"],
            },
            {
                access: 5,
                category: "diagnostic",
                description: "Remaining battery in %",
                label: "Battery",
                name: "battery",
                property: "battery",
                type: "numeric",
                unit: "%",
                value_max: 100,
                value_min: 0,
            },
            {
                access: 5,
                category: "diagnostic",
                description: "Reported battery voltage in millivolts",
                label: "Voltage",
                name: "voltage",
                property: "voltage",
                type: "numeric",
                unit: "mV",
            },
            {
                access: 1,
                category: "diagnostic",
                description: "Link quality (signal strength)",
                label: "Linkquality",
                name: "linkquality",
                property: "linkquality",
                type: "numeric",
                unit: "lqi",
                value_max: 255,
                value_min: 0,
            },
        ],
        model: "E2134",
        options: [
            {
                access: 2,
                description: "Calibrates the illuminance value (percentual offset), takes into effect on next report of device.",
                label: "Illuminance calibration",
                name: "illuminance_calibration",
                property: "illuminance_calibration",
                type: "numeric",
                value_step: 0.1,
            },
            {
                access: 2,
                description:
                    "Sets the duration of the identification procedure in seconds (i.e., how long the device would flash).The value ranges from 1 to 30 seconds (default: 3).",
                label: "Identify timeout",
                name: "identify_timeout",
                property: "identify_timeout",
                type: "numeric",
                value_max: 30,
                value_min: 1,
            },
            {
                access: 2,
                description:
                    'Sends a message after the last time no occupancy (occupancy: false) was detected. When setting this for example to [10, 60] a `{"no_occupancy_since": 10}` will be send after 10 seconds and a `{"no_occupancy_since": 60}` after 60 seconds.',
                // @ts-expect-error bad ZHC typing
                item_type: {
                    access: 3,
                    label: "Time",
                    name: "time",
                    type: "numeric",
                },
                label: "No occupancy since",
                name: "no_occupancy_since",
                property: "no_occupancy_since",
                type: "list",
            },
            {
                access: 2,
                description: "Expose the raw illuminance value.",
                label: "Illuminance raw",
                name: "illuminance_raw",
                property: "illuminance_raw",
                type: "binary",
                value_off: false,
                value_on: true,
            },
        ],
        source: "native",
        supports_ota: true,
        vendor: "IKEA",
    },
    disabled: false,
    endpoints: {
        "1": {
            bindings: [
                {
                    cluster: "genPollCtrl",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x847127fffedfe3cd",
                        type: "endpoint",
                    },
                },
                {
                    cluster: "genPowerCfg",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x847127fffedfe3cd",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: [
                    "genBasic",
                    "genPowerCfg",
                    "genIdentify",
                    "genPollCtrl",
                    "haDiagnostic",
                    "touchlink",
                    "manuSpecificIkeaUnknown",
                    "heimanSpecificAirQuality",
                ],
                output: ["genIdentify", "genGroups", "genOnOff", "genOta", "touchlink"],
            },
            configured_reportings: [
                {
                    attribute: "batteryPercentageRemaining",
                    cluster: "genPowerCfg",
                    maximum_report_interval: 65000,
                    minimum_report_interval: 3600,
                    reportable_change: 10,
                },
                {
                    attribute: "batteryVoltage",
                    cluster: "genPowerCfg",
                    maximum_report_interval: 65000,
                    minimum_report_interval: 3600,
                    reportable_change: 10,
                },
            ],
            scenes: [],
        },
        "2": {
            bindings: [
                {
                    cluster: "msOccupancySensing",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x847127fffedfe3cd",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: ["genBasic", "genIdentify", "msOccupancySensing"],
                output: ["genIdentify"],
            },
            configured_reportings: [
                {
                    attribute: "occupancy",
                    cluster: "msOccupancySensing",
                    maximum_report_interval: 3600,
                    minimum_report_interval: 0,
                    reportable_change: 0,
                },
            ],
            scenes: [],
        },
        "3": {
            bindings: [
                {
                    cluster: "msIlluminanceMeasurement",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x847127fffedfe3cd",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: ["genBasic", "genIdentify", "msIlluminanceMeasurement"],
                output: ["genIdentify"],
            },
            configured_reportings: [
                {
                    attribute: "measuredValue",
                    cluster: "msIlluminanceMeasurement",
                    maximum_report_interval: 3600,
                    minimum_report_interval: 10,
                    reportable_change: 5,
                },
            ],
            scenes: [],
        },
    },
    friendly_name: "Détecteur_Mouvement_Bureau",
    ieee_address: "0x94a081fffe57bbf6",
    interview_completed: true,
    interview_state: InterviewState.Successful,
    interviewing: false,
    manufacturer: "IKEA of Sweden",
    model_id: "VALLHORN Wireless Motion Sensor",
    network_address: 22393,
    power_source: "Battery",
    software_build_id: "1.0.64",
    supported: true,
    type: "EndDevice",
};

export const OTHER_ROUTER: Device = {
    date_code: "",
    // @ts-expect-error icon bad Z2M typing
    definition: {
        description: "Clamp meter",
        exposes: [
            {
                access: 1,
                description: "Instantaneous measured electrical current",
                label: "Current",
                name: "current",
                property: "current",
                type: "numeric",
                unit: "A",
            },
            {
                access: 1,
                description: "Instantaneous measured power",
                label: "Power",
                name: "power",
                property: "power",
                type: "numeric",
                unit: "W",
            },
            {
                access: 1,
                description: "Measured electrical potential value",
                label: "Voltage",
                name: "voltage",
                property: "voltage",
                type: "numeric",
                unit: "V",
            },
            {
                access: 1,
                description: "Sum of consumed energy",
                label: "Energy",
                name: "energy",
                property: "energy",
                type: "numeric",
                unit: "kWh",
            },
            {
                access: 1,
                category: "diagnostic",
                description: "Link quality (signal strength)",
                label: "Linkquality",
                name: "linkquality",
                property: "linkquality",
                type: "numeric",
                unit: "lqi",
                value_max: 255,
                value_min: 0,
            },
        ],
        model: "PJ-MGW1203",
        options: [
            {
                access: 2,
                description: "Calibrates the current value (percentual offset), takes into effect on next report of device.",
                label: "Current calibration",
                name: "current_calibration",
                property: "current_calibration",
                type: "numeric",
                value_step: 0.1,
            },
            {
                access: 2,
                description:
                    "Number of digits after decimal point for current, takes into effect on next report of device. This option can only decrease the precision, not increase it.",
                label: "Current precision",
                name: "current_precision",
                property: "current_precision",
                type: "numeric",
                value_max: 3,
                value_min: 0,
            },
            {
                access: 2,
                description: "Calibrates the power value (percentual offset), takes into effect on next report of device.",
                label: "Power calibration",
                name: "power_calibration",
                property: "power_calibration",
                type: "numeric",
                value_step: 0.1,
            },
            {
                access: 2,
                description:
                    "Number of digits after decimal point for power, takes into effect on next report of device. This option can only decrease the precision, not increase it.",
                label: "Power precision",
                name: "power_precision",
                property: "power_precision",
                type: "numeric",
                value_max: 3,
                value_min: 0,
            },
            {
                access: 2,
                description: "Calibrates the voltage value (percentual offset), takes into effect on next report of device.",
                label: "Voltage calibration",
                name: "voltage_calibration",
                property: "voltage_calibration",
                type: "numeric",
                value_step: 0.1,
            },
            {
                access: 2,
                description:
                    "Number of digits after decimal point for voltage, takes into effect on next report of device. This option can only decrease the precision, not increase it.",
                label: "Voltage precision",
                name: "voltage_precision",
                property: "voltage_precision",
                type: "numeric",
                value_max: 3,
                value_min: 0,
            },
            {
                access: 2,
                description: "Calibrates the energy value (percentual offset), takes into effect on next report of device.",
                label: "Energy calibration",
                name: "energy_calibration",
                property: "energy_calibration",
                type: "numeric",
                value_step: 0.1,
            },
            {
                access: 2,
                description:
                    "Number of digits after decimal point for energy, takes into effect on next report of device. This option can only decrease the precision, not increase it.",
                label: "Energy precision",
                name: "energy_precision",
                property: "energy_precision",
                type: "numeric",
                value_max: 3,
                value_min: 0,
            },
        ],
        source: "native",
        supports_ota: false,
        vendor: "Tuya",
    },
    disabled: false,
    endpoints: {
        "1": {
            bindings: [],
            clusters: {
                input: ["genBasic", "genGroups", "genScenes", "manuSpecificTuya"],
                output: ["genOta", "genTime"],
            },
            configured_reportings: [],
            scenes: [],
        },
    },
    friendly_name: "Solar Power Meter",
    ieee_address: "0x70ac08fff0123456",
    interview_completed: true,
    interview_state: InterviewState.Successful,
    interviewing: false,
    manufacturer: "_TZE204_cjbofhxw",
    model_id: "TS0601",
    network_address: 37330,
    power_source: "Mains (single phase)",
    supported: true,
    type: "Router",
};

export const COMPLEX_EXPOSES_ENDDEVICE: Device = {
    date_code: "20240820",
    definition: {
        source: "native",
        description: "Zigbee smart water valve",
        exposes: [
            {
                access: 1,
                description: "Current water flow",
                label: "Flow",
                name: "flow",
                property: "flow",
                type: "numeric",
                unit: "m³/h",
            },
            {
                access: 5,
                category: "diagnostic",
                description: "Remaining battery in %",
                label: "Battery",
                name: "battery",
                property: "battery",
                type: "numeric",
                unit: "%",
                value_max: 100,
                value_min: 0,
            },
            // @ts-expect-error bad ZHC typing
            {
                features: [
                    {
                        access: 7,
                        description: "On/off state of the switch",
                        label: "State",
                        name: "state",
                        property: "state",
                        type: "binary",
                        value_off: "OFF",
                        value_on: "ON",
                        value_toggle: "TOGGLE",
                    },
                ],
                type: "switch",
            },
            {
                access: 5,
                description: "The water valve is in normal state, water shortage or water leakage",
                label: "Current device status",
                name: "current_device_status",
                property: "current_device_status",
                type: "enum",
                values: ["normal_state", "water_shortage", "water_leakage", "water_shortage & water_leakage"],
            },
            {
                access: 7,
                description:
                    "Automatically shut down the water valve after the water shortage exceeds 30 minutes. Requires firmware version 1.0.4 or later!",
                label: "Auto close when water shortage",
                name: "auto_close_when_water_shortage",
                property: "auto_close_when_water_shortage",
                type: "binary",
                value_off: "DISABLE",
                value_on: "ENABLE",
            },
            {
                access: 7,
                description: "Smart water valve cycle timing irrigation",
                features: [
                    {
                        access: 1,
                        description: "Number of times it has been executed",
                        label: "Current count",
                        name: "current_count",
                        property: "current_count",
                        type: "numeric",
                        unit: "times",
                    },
                    {
                        access: 3,
                        description: "Total times of circulating irrigation",
                        label: "Total number",
                        name: "total_number",
                        property: "total_number",
                        type: "numeric",
                        unit: "times",
                        value_max: 100,
                        value_min: 0,
                    },
                    {
                        access: 3,
                        description: "Single irrigation duration",
                        label: "Irrigation duration",
                        name: "irrigation_duration",
                        property: "irrigation_duration",
                        type: "numeric",
                        unit: "seconds",
                        value_max: 86400,
                        value_min: 0,
                    },
                    {
                        access: 3,
                        description: "Time interval between two adjacent irrigation",
                        label: "Irrigation interval",
                        name: "irrigation_interval",
                        property: "irrigation_interval",
                        type: "numeric",
                        unit: "seconds",
                        value_max: 86400,
                        value_min: 0,
                    },
                ],
                label: "Cyclic timed irrigation",
                name: "cyclic_timed_irrigation",
                property: "cyclic_timed_irrigation",
                type: "composite",
            },
            {
                access: 7,
                description: "Smart water valve circulating quantitative irrigation",
                features: [
                    {
                        access: 1,
                        description: "Number of times it has been executed",
                        label: "Current count",
                        name: "current_count",
                        property: "current_count",
                        type: "numeric",
                        unit: "times",
                    },
                    {
                        access: 3,
                        description: "Total times of circulating irrigation",
                        label: "Total number",
                        name: "total_number",
                        property: "total_number",
                        type: "numeric",
                        unit: "times",
                        value_max: 100,
                        value_min: 0,
                    },
                    {
                        access: 3,
                        description: "Single irrigation capacity",
                        label: "Irrigation capacity",
                        name: "irrigation_capacity",
                        property: "irrigation_capacity",
                        type: "numeric",
                        unit: "liter",
                        value_max: 6500,
                        value_min: 0,
                    },
                    {
                        access: 3,
                        description: "Time interval between two adjacent irrigation",
                        label: "Irrigation interval",
                        name: "irrigation_interval",
                        property: "irrigation_interval",
                        type: "numeric",
                        unit: "seconds",
                        value_max: 86400,
                        value_min: 0,
                    },
                ],
                label: "Cyclic quantitative irrigation",
                name: "cyclic_quantitative_irrigation",
                property: "cyclic_quantitative_irrigation",
                type: "composite",
            },
            {
                access: 1,
                category: "diagnostic",
                description: "Link quality (signal strength)",
                label: "Linkquality",
                name: "linkquality",
                property: "linkquality",
                type: "numeric",
                unit: "lqi",
                value_max: 255,
                value_min: 0,
            },
        ],
        model: "SWV",
        options: [
            {
                access: 2,
                description: "State actions will also be published as 'action' when true (default false).",
                label: "State action",
                name: "state_action",
                property: "state_action",
                type: "binary",
                value_off: false,
                value_on: true,
            },
        ],
        supports_ota: true,
        vendor: "SONOFF",
    },
    disabled: false,
    endpoints: {
        "1": {
            bindings: [
                {
                    cluster: "genPollCtrl",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x8c8b48fffe461952",
                        type: "endpoint",
                    },
                },
                {
                    cluster: "genPowerCfg",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x8c8b48fffe461952",
                        type: "endpoint",
                    },
                },
                {
                    cluster: "genOnOff",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x8c8b48fffe461952",
                        type: "endpoint",
                    },
                },
                {
                    cluster: "msFlowMeasurement",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x8c8b48fffe461952",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: [
                    "genBasic",
                    "genPowerCfg",
                    "genIdentify",
                    "genOnOff",
                    "genPollCtrl",
                    "msFlowMeasurement",
                    "haDiagnostic",
                    "manuSpecificAmazonWWAH",
                    "customClusterEwelink",
                ],
                output: ["genTime", "genOta"],
            },
            configured_reportings: [
                {
                    attribute: "batteryPercentageRemaining",
                    cluster: "genPowerCfg",
                    maximum_report_interval: 65000,
                    minimum_report_interval: 3600,
                    reportable_change: 10,
                },
                {
                    attribute: "onOff",
                    cluster: "genOnOff",
                    maximum_report_interval: 65000,
                    minimum_report_interval: 0,
                    reportable_change: 1,
                },
            ],
            scenes: [],
        },
    },
    friendly_name: "Irrigation-back-3",
    ieee_address: "0x44e2f8fffe0c0ea6",
    interview_completed: true,
    interview_state: InterviewState.Successful,
    interviewing: false,
    manufacturer: "SONOFF",
    model_id: "SWV",
    network_address: 63113,
    power_source: "Battery",
    software_build_id: "1.0.4",
    supported: true,
    type: "EndDevice",
};

export const MULTI_ENDPOINT_ROUTER: Device = {
    date_code: "20240902",
    definition: {
        source: "native",
        description: "Hue Twilight sleep and wake-up light white",
        exposes: [
            // @ts-expect-error bad ZHC typing
            {
                endpoint: "front",
                features: [
                    {
                        access: 7,
                        description: "On/off state of this light",
                        endpoint: "front",
                        label: "State",
                        name: "state",
                        property: "state_front",
                        type: "binary",
                        value_off: "OFF",
                        value_on: "ON",
                        value_toggle: "TOGGLE",
                    },
                    {
                        access: 7,
                        description: "Brightness of this light",
                        endpoint: "front",
                        label: "Brightness",
                        name: "brightness",
                        property: "brightness_front",
                        type: "numeric",
                        value_max: 254,
                        value_min: 0,
                    },
                    {
                        access: 7,
                        description: "Color temperature of this light",
                        endpoint: "front",
                        label: "Color temp",
                        name: "color_temp",
                        presets: [
                            {
                                description: "Coolest temperature supported",
                                name: "coolest",
                                value: 153,
                            },
                            {
                                description: "Cool temperature (250 mireds / 4000 Kelvin)",
                                name: "cool",
                                value: 250,
                            },
                            {
                                description: "Neutral temperature (370 mireds / 2700 Kelvin)",
                                name: "neutral",
                                value: 370,
                            },
                            {
                                description: "Warm temperature (454 mireds / 2200 Kelvin)",
                                name: "warm",
                                value: 454,
                            },
                            {
                                description: "Warmest temperature supported",
                                name: "warmest",
                                value: 500,
                            },
                        ],
                        property: "color_temp_front",
                        type: "numeric",
                        unit: "mired",
                        value_max: 500,
                        value_min: 153,
                    },
                    {
                        access: 7,
                        description: "Color temperature after cold power on of this light",
                        endpoint: "front",
                        label: "Color temp startup",
                        name: "color_temp_startup",
                        presets: [
                            {
                                description: "Coolest temperature supported",
                                name: "coolest",
                                value: 153,
                            },
                            {
                                description: "Cool temperature (250 mireds / 4000 Kelvin)",
                                name: "cool",
                                value: 250,
                            },
                            {
                                description: "Neutral temperature (370 mireds / 2700 Kelvin)",
                                name: "neutral",
                                value: 370,
                            },
                            {
                                description: "Warm temperature (454 mireds / 2200 Kelvin)",
                                name: "warm",
                                value: 454,
                            },
                            {
                                description: "Warmest temperature supported",
                                name: "warmest",
                                value: 500,
                            },
                            {
                                description: "Restore previous color_temp on cold power on",
                                name: "previous",
                                value: 65535,
                            },
                        ],
                        property: "color_temp_startup_front",
                        type: "numeric",
                        unit: "mired",
                        value_max: 500,
                        value_min: 153,
                    },
                    {
                        access: 7,
                        description: "Color of this light in the CIE 1931 color space (x/y)",
                        endpoint: "front",
                        features: [
                            {
                                access: 7,
                                endpoint: "front",
                                label: "X",
                                name: "x",
                                property: "x_front",
                                type: "numeric",
                            },
                            {
                                access: 7,
                                endpoint: "front",
                                label: "Y",
                                name: "y",
                                property: "y_front",
                                type: "numeric",
                            },
                        ],
                        label: "Color (X/Y)",
                        name: "color_xy",
                        property: "color_front",
                        type: "composite",
                    },
                    {
                        access: 7,
                        description: "Color of this light expressed as hue/saturation",
                        endpoint: "front",
                        features: [
                            {
                                access: 7,
                                endpoint: "front",
                                label: "Hue",
                                name: "hue",
                                property: "hue_front",
                                type: "numeric",
                            },
                            {
                                access: 7,
                                endpoint: "front",
                                label: "Saturation",
                                name: "saturation",
                                property: "saturation_front",
                                type: "numeric",
                            },
                        ],
                        label: "Color (HS)",
                        name: "color_hs",
                        property: "color_front",
                        type: "composite",
                    },
                ],
                type: "light",
            },
            {
                access: 7,
                category: "config",
                description: "Controls the behavior when the device is powered on after power loss",
                endpoint: "front",
                label: "Power-on behavior",
                name: "power_on_behavior",
                property: "power_on_behavior_front",
                type: "enum",
                values: ["off", "on", "toggle", "previous"],
            },
            {
                access: 2,
                endpoint: "front",
                label: "Effect",
                name: "effect",
                property: "effect_front",
                type: "enum",
                values: [
                    "blink",
                    "breathe",
                    "okay",
                    "channel_change",
                    "candle",
                    "fireplace",
                    "colorloop",
                    "finish_effect",
                    "stop_effect",
                    "stop_hue_effect",
                ],
            },
            // @ts-expect-error bad ZHC typing
            {
                endpoint: "back",
                features: [
                    {
                        access: 7,
                        description: "On/off state of this light",
                        endpoint: "back",
                        label: "State",
                        name: "state",
                        property: "state_back",
                        type: "binary",
                        value_off: "OFF",
                        value_on: "ON",
                        value_toggle: "TOGGLE",
                    },
                    {
                        access: 7,
                        description: "Brightness of this light",
                        endpoint: "back",
                        label: "Brightness",
                        name: "brightness",
                        property: "brightness_back",
                        type: "numeric",
                        value_max: 254,
                        value_min: 0,
                    },
                    {
                        access: 7,
                        description: "Color temperature of this light",
                        endpoint: "back",
                        label: "Color temp",
                        name: "color_temp",
                        presets: [
                            {
                                description: "Coolest temperature supported",
                                name: "coolest",
                                value: 153,
                            },
                            {
                                description: "Cool temperature (250 mireds / 4000 Kelvin)",
                                name: "cool",
                                value: 250,
                            },
                            {
                                description: "Neutral temperature (370 mireds / 2700 Kelvin)",
                                name: "neutral",
                                value: 370,
                            },
                            {
                                description: "Warm temperature (454 mireds / 2200 Kelvin)",
                                name: "warm",
                                value: 454,
                            },
                            {
                                description: "Warmest temperature supported",
                                name: "warmest",
                                value: 500,
                            },
                        ],
                        property: "color_temp_back",
                        type: "numeric",
                        unit: "mired",
                        value_max: 500,
                        value_min: 153,
                    },
                    {
                        access: 7,
                        description: "Color temperature after cold power on of this light",
                        endpoint: "back",
                        label: "Color temp startup",
                        name: "color_temp_startup",
                        presets: [
                            {
                                description: "Coolest temperature supported",
                                name: "coolest",
                                value: 153,
                            },
                            {
                                description: "Cool temperature (250 mireds / 4000 Kelvin)",
                                name: "cool",
                                value: 250,
                            },
                            {
                                description: "Neutral temperature (370 mireds / 2700 Kelvin)",
                                name: "neutral",
                                value: 370,
                            },
                            {
                                description: "Warm temperature (454 mireds / 2200 Kelvin)",
                                name: "warm",
                                value: 454,
                            },
                            {
                                description: "Warmest temperature supported",
                                name: "warmest",
                                value: 500,
                            },
                            {
                                description: "Restore previous color_temp on cold power on",
                                name: "previous",
                                value: 65535,
                            },
                        ],
                        property: "color_temp_startup_back",
                        type: "numeric",
                        unit: "mired",
                        value_max: 500,
                        value_min: 153,
                    },
                    {
                        access: 7,
                        description: "Color of this light in the CIE 1931 color space (x/y)",
                        endpoint: "back",
                        features: [
                            {
                                access: 7,
                                endpoint: "back",
                                label: "X",
                                name: "x",
                                property: "x_back",
                                type: "numeric",
                            },
                            {
                                access: 7,
                                endpoint: "back",
                                label: "Y",
                                name: "y",
                                property: "y_back",
                                type: "numeric",
                            },
                        ],
                        label: "Color (X/Y)",
                        name: "color_xy",
                        property: "color_back",
                        type: "composite",
                    },
                    {
                        access: 7,
                        description: "Color of this light expressed as hue/saturation",
                        endpoint: "back",
                        features: [
                            {
                                access: 7,
                                endpoint: "back",
                                label: "Hue",
                                name: "hue",
                                property: "hue_back",
                                type: "numeric",
                            },
                            {
                                access: 7,
                                endpoint: "back",
                                label: "Saturation",
                                name: "saturation",
                                property: "saturation_back",
                                type: "numeric",
                            },
                        ],
                        label: "Color (HS)",
                        name: "color_hs",
                        property: "color_back",
                        type: "composite",
                    },
                ],
                type: "light",
            },
            {
                access: 7,
                category: "config",
                description: "Controls the behavior when the device is powered on after power loss",
                endpoint: "back",
                label: "Power-on behavior",
                name: "power_on_behavior",
                property: "power_on_behavior_back",
                type: "enum",
                values: ["off", "on", "toggle", "previous"],
            },
            {
                access: 2,
                endpoint: "back",
                label: "Gradient scene",
                name: "gradient_scene",
                property: "gradient_scene_back",
                type: "enum",
                values: [
                    "blossom",
                    "crocus",
                    "precious",
                    "narcissa",
                    "beginnings",
                    "first_light",
                    "horizon",
                    "valley_dawn",
                    "sunflare",
                    "emerald_flutter",
                    "memento",
                    "resplendent",
                    "scarlet_dream",
                    "lovebirds",
                    "smitten",
                    "glitz_and_glam",
                    "promise",
                    "ruby_romance",
                    "city_of_love",
                    "honolulu",
                    "savanna_sunset",
                    "golden_pond",
                    "runy_glow",
                    "tropical_twilight",
                    "miami",
                    "cancun",
                    "rio",
                    "chinatown",
                    "ibiza",
                    "osaka",
                    "tokyo",
                    "motown",
                    "fairfax",
                    "galaxy",
                    "starlight",
                    "blood moon",
                    "artic_aurora",
                    "moonlight",
                    "nebula",
                    "sundown",
                    "blue_lagoon",
                    "palm_beach",
                    "lake_placid",
                    "mountain_breeze",
                    "lake_mist",
                    "ocean_dawn",
                    "frosty_dawn",
                    "sunday_morning",
                    "emerald_isle",
                    "spring_blossom",
                    "midsummer_sun",
                    "autumn_gold",
                    "spring_lake",
                    "winter_mountain",
                    "midwinter",
                    "amber_bloom",
                    "lily",
                    "painted_sky",
                    "winter_beauty",
                    "orange_fields",
                    "forest_adventure",
                    "blue_planet",
                    "soho",
                    "vapor_wave",
                    "magneto",
                    "tyrell",
                    "disturbia",
                    "hal",
                    "golden_star",
                    "under_the_tree",
                    "silent_night",
                    "rosy_sparkle",
                    "festive_fun",
                    "colour_burst",
                    "crystalline",
                ],
            },
            {
                access: 7,
                description: "List of RGB HEX colors",
                endpoint: "back",
                // @ts-expect-error bad ZHC typing
                item_type: {
                    access: 7,
                    description: "Color in RGB HEX format (eg #663399)",
                    label: "Hex",
                    name: "hex",
                    type: "text",
                },
                label: "Gradient",
                length_max: 9,
                length_min: 1,
                name: "gradient",
                property: "gradient_back",
                type: "list",
            },
            {
                access: 2,
                endpoint: "back",
                label: "Effect",
                name: "effect",
                property: "effect_back",
                type: "enum",
                values: [
                    "blink",
                    "breathe",
                    "okay",
                    "channel_change",
                    "candle",
                    "fireplace",
                    "colorloop",
                    "sunrise",
                    "finish_effect",
                    "stop_effect",
                    "stop_hue_effect",
                ],
            },
            {
                access: 1,
                category: "diagnostic",
                description: "Triggered action (e.g. a button click)",
                label: "Action",
                name: "action",
                property: "action",
                type: "enum",
                values: [
                    "dot_press",
                    "dot_hold",
                    "dot_press_release",
                    "dot_hold_release",
                    "hue_press",
                    "hue_hold",
                    "hue_press_release",
                    "hue_hold_release",
                ],
            },
            {
                access: 1,
                category: "diagnostic",
                description: "Link quality (signal strength)",
                label: "Linkquality",
                name: "linkquality",
                property: "linkquality",
                type: "numeric",
                unit: "lqi",
                value_max: 255,
                value_min: 0,
            },
        ],
        model: "929003711201",
        options: [
            {
                access: 2,
                description:
                    "Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).",
                label: "Transition",
                name: "transition",
                property: "transition",
                type: "numeric",
                value_min: 0,
            },
            {
                access: 2,
                description:
                    "When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).",
                label: "Color sync",
                name: "color_sync",
                property: "color_sync",
                type: "binary",
                value_off: false,
                value_on: true,
            },
            {
                access: 2,
                description: "State actions will also be published as 'action' when true (default false).",
                label: "State action",
                name: "state_action",
                property: "state_action",
                type: "binary",
                value_off: false,
                value_on: true,
            },
        ],
        supports_ota: true,
        vendor: "Philips",
    },
    disabled: false,
    endpoints: {
        "1": {
            name: "switch",
            bindings: [
                {
                    cluster: "genOnOff",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x00124b0029e8b9ae",
                        type: "endpoint",
                    },
                },
                {
                    cluster: "manuSpecificPhilips",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x00124b0029e8b9ae",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: ["genBasic", "manuSpecificPhilips", "genIdentify"],
                output: ["genOnOff", "genIdentify"],
            },
            configured_reportings: [],
            scenes: [],
        },
        "11": {
            name: "back",
            bindings: [
                {
                    cluster: "manuSpecificPhilips2",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x00124b0029e8b9ae",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: [
                    "genBasic",
                    "genIdentify",
                    "genGroups",
                    "genScenes",
                    "genOnOff",
                    "genLevelCtrl",
                    "touchlink",
                    "manuSpecificPhilips2",
                    "lightingColorCtrl",
                    "manuSpecificPhilips3",
                    "manuSpecificSchneiderFanSwitchConfiguration",
                ],
                output: ["genOta"],
            },
            configured_reportings: [],
            scenes: [],
        },
        "12": {
            name: "front",
            bindings: [
                {
                    cluster: "manuSpecificPhilips2",
                    target: {
                        endpoint: 1,
                        ieee_address: "0x00124b0029e8b9ae",
                        type: "endpoint",
                    },
                },
            ],
            clusters: {
                input: [
                    "genBasic",
                    "genIdentify",
                    "genGroups",
                    "genScenes",
                    "genOnOff",
                    "genLevelCtrl",
                    "manuSpecificPhilips2",
                    "lightingColorCtrl",
                    "manuSpecificPhilips3",
                ],
                output: [],
            },
            configured_reportings: [],
            scenes: [],
        },
        "242": {
            bindings: [],
            clusters: {
                input: [],
                output: ["greenPower"],
            },
            configured_reportings: [],
            scenes: [],
        },
    },
    friendly_name: "some/lamp",
    ieee_address: "0x00abcdef12345678",
    interview_completed: true,
    interview_state: InterviewState.Successful,
    interviewing: false,
    manufacturer: "Signify Netherlands B.V.",
    model_id: "LGT001",
    network_address: 7961,
    power_source: "Mains (single phase)",
    software_build_id: "1.122.2",
    supported: true,
    type: "Router",
};

export const BASIC_ROUTER_STATE: DeviceState = {
    state: true,
};

export const BASIC_ENDDEVICE_STATE: DeviceState = {
    battery: 86,
    illuminance: 15,
    illuminance_raw: 6989,
    occupancy: false,
};

export const OTHER_ROUTER_STATE: DeviceState = {
    current: 0.051,
    energy: 0.01,
    power: 1.9,
    voltage: 245.1,
};

export const COMPLEX_EXPOSES_ENDDEVICE_STATE: DeviceState = {
    auto_close_when_water_shortage: "ENABLE",
    battery: 100,
    current_device_status: "normal_state",
    flow: 0,
    state: "OFF",
};

export const MULTI_ENDPOINT_ROUTER_STATE: DeviceState = {
    brightness_back: 254,
    brightness_front: 254,
    color: {
        h: 32,
        hue: 32,
        s: 81,
        saturation: 81,
        x: 0.4574,
        y: 0.41,
    },
    color_back: {
        hue: 20,
        saturation: 63,
        x: 0.4264,
        y: 0.3611,
    },
    color_front: {
        hue: 20,
        saturation: 63,
        x: 0.4264,
        y: 0.3611,
    },
    color_mode: "color_temp",
    color_mode_back: "xy",
    color_mode_front: "xy",
    color_temp: 366,
    color_temp_back: 357,
    color_temp_front: 357,
    color_temp_startup: 366,
    color_temp_startup_back: 65535,
    color_temp_startup_front: 65535,
    power_on_behavior_back: "on",
    power_on_behavior_front: "on",
    state_back: "OFF",
    state_front: "OFF",
};
