import type { Zigbee2MQTTAPI } from "zigbee2mqtt";
import type { Message } from "../src/types.js";

// NOTE: timestamp is generated by frontend on receipt
export const BRIDGE_LOGGING: Message<Omit<Zigbee2MQTTAPI["bridge/logging"], "timestamp">>[] = [
    {
        payload: {
            level: "info",
            message: "z2m: Zigbee: allowing new devices to join.",
            namespace: "z2m",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "debug",
            message: `zh:ember:ezsp: ===> [FRAME: ID=273:"IMPORT_TRANSIENT_KEY" Seq=44 Len=29]`,
            namespace: "zh:ember:ezsp",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "debug",
            message: `zh:ember:ezsp: <=== [FRAME: ID=273:"IMPORT_TRANSIENT_KEY" Seq=44 Len=9]`,
            namespace: "zh:ember:ezsp",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "info",
            message: `z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb43a31fffe0f6aae","ieee_address":"0xb43a31fffe0f6aae"},"type":"device_joined"}`,
            namespace: "z2m:mqtt",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "info",
            message: `z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb43a31fffe0f6aae","ieee_address":"0xb43a31fffe0f6aae","status":"started"},"type":"device_interview"}'`,
            namespace: "z2m:mqtt",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "error",
            message: `z2m: Request 'zigbee2mqtt/bridge/request/device/remove' failed with error: 'Failed to remove device '0x588e81fffe23317f' (block: false, force: false) (Error: Timeout after 15000ms [sender=3867 clusterId=32820 cmdId=undefined])'`,
            namespace: "z2m",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "warning",
            message: `z2m: Device '0x588e81fffe23317f' left the network`,
            namespace: "z2m",
        },
        topic: "bridge/logging",
    },
    {
        payload: {
            level: "warning",
            message: `z2m: Failed to ping '0xb43a31fffe0f6aae' (attempt 1/1, ZCL command 0xb43a31fffe0f6aae/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout after 10000ms [sender=57129 clusterId=0 cmdId=1]))`,
            namespace: "z2m",
        },
        topic: "bridge/logging",
    },
];

export const BRIDGE_LOGGING_READ_ATTR: Message<Omit<Zigbee2MQTTAPI["bridge/logging"], "timestamp">> = {
    payload: {
        level: "info",
        message: `zhc:tz: Read result of 'genBasic': {"modelId": "abcd"}`,
        namespace: "zhc:tz",
    },
    topic: "bridge/logging",
};

export const BRIDGE_LOGGING_EXECUTE_COMMAND: Message<Omit<Zigbee2MQTTAPI["bridge/logging"], "timestamp">> = {
    payload: {
        level: "info",
        message: `zhc:tz: Invoked 'genBasic.1' with payload '{"a": 1}'`,
        namespace: "zhc:tz",
    },
    topic: "bridge/logging",
};
